### ISSUE TITLE
Conditional recipes

### ISSUE THREAD

**Issue by jonesbusy** [jenkins-infra/plugin-modernizer-tool#320]
### What feature do you want to see added?

The `recipes.yml` is a quite flat structure of recipes that OpenRewrite can understand.

But we cannot just apply recipes blindly on all plugins because they depend on the context and the nature of the plugin

The idea is to build some simple rules based on `PluginMetadata` flag

One very simple example (We need to see about the format. File ? Directly on the code ?)

```yaml
rules:
    - recipe: AddGitHubSecurityWorlfow
      conditions:
         - "not IS_API_PLUGIN"
         - "HAS_SOURCE_FILE"
```
